- name: change hostname to re-je
  hostname:
    name: "re-je"

- name: add re-je to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost re-je"
    state: present

- name: Install the full apt sources
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0644"

- name: Update package lists
  apt: update_cache=yes

- name: Installing locales package
  apt: name=locales

- name: Setting locale
  command: locale-gen en_GB.UTF-8

- name: Update all packages to the latest version
  apt: upgrade=dist

- name: Update all packages to the latest version
  command: update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX
